# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 690b9219f97cda6fbb5452b8ec4115cfc98648bb719536f7a39adb2b96409d366fcb88819753bde8a1d60d5a1bef4ca2fb422cc9e737fe7aa460389c8e4bea4d

test:
  secret_key_base: ed93ff2fadd35a7fdf8fa5fe6904228740961cd20fa753ab9d6d1b22c99d58bb181e794244933cd4ad3ea8e59fb074bc4728484b5428d35444b48b3f3684ee87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
